name: frontend
description: "A new mbti project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  shared_preferences: ^2.2.2
  kakao_map_plugin: ^0.3.7
  geolocator: ^13.0.1
  tosspayments_webview_flutter: ^1.0.6
  flutter_dotenv: ^5.1.0

  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.product
    - .env.local